// GENERATED by scripts/select-edition.mjs — do not edit.
// Default committed state targets the certified backend so a plain build,
// `npm test`, and a fresh clone all compile the real sanitizer.
export * from './backend.certified';
