table stylesheet
	lineageTag: 5c1f3480-6fe0-48c8-999f-ea7b8045fe08

	measure 'Theme Color Probe' = ```
			
			"<style>" &
			".tcp{font:11px 'Segoe UI',sans-serif;display:flex;flex-direction:column;gap:14px;padding:4px}" &
			".tcp .hcflag{display:none;font-weight:700;color:var(--pbi-theme-fg,#000)}" &
			".pbi-theme-hc .tcp .hcflag{display:block}" &
			".grp{display:flex;flex-direction:column;gap:6px}" &
			".grp>h4{margin:0;font-size:10px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:var(--pbi-theme-fg-neutral-secondary,#605e5c)}" &
			".sw{display:flex;flex-wrap:wrap;gap:6px}" &
			".s{width:92px;height:54px;border:1px solid #ccc;border-radius:4px;display:flex;align-items:flex-end;padding:3px;box-sizing:border-box;forced-color-adjust:none}" &
			".s span{background:rgba(255,255,255,.8);padding:0 3px;border-radius:2px}" &
			".c1{background:var(--pbi-theme-color-1,var(--pbi-theme-fg,transparent))}" &
			".c2{background:var(--pbi-theme-color-2,var(--pbi-theme-fg,transparent))}" &
			".c3{background:var(--pbi-theme-color-3,var(--pbi-theme-fg,transparent))}" &
			".c4{background:var(--pbi-theme-color-4,var(--pbi-theme-fg,transparent))}" &
			".c5{background:var(--pbi-theme-color-5,var(--pbi-theme-fg,transparent))}" &
			".c6{background:var(--pbi-theme-color-6,var(--pbi-theme-fg,transparent))}" &
			".c7{background:var(--pbi-theme-color-7,var(--pbi-theme-fg,transparent))}" &
			".c8{background:var(--pbi-theme-color-8,var(--pbi-theme-fg,transparent))}" &
			".c9{background:var(--pbi-theme-color-9,var(--pbi-theme-fg,transparent))}" &
			".c10{background:var(--pbi-theme-color-10,var(--pbi-theme-fg,transparent))}" &
			".c11{background:var(--pbi-theme-color-11,var(--pbi-theme-fg,transparent))}" &
			".c12{background:var(--pbi-theme-color-12,var(--pbi-theme-fg,transparent))}" &
			".ngood{background:var(--pbi-theme-good,transparent)}" &
			".nbad{background:var(--pbi-theme-bad,transparent)}" &
			".nneu{background:var(--pbi-theme-neutral,transparent)}" &
			".nmin{background:var(--pbi-theme-min,transparent)}" &
			".ncenter{background:var(--pbi-theme-center,transparent)}" &
			".nmax{background:var(--pbi-theme-max,transparent)}" &
			".nfg{background:var(--pbi-theme-fg,transparent)}" &
			".nfgs{background:var(--pbi-theme-fg-neutral-secondary,transparent)}" &
			".nfgt{background:var(--pbi-theme-fg-neutral-tertiary,transparent)}" &
			".nbg{background:var(--pbi-theme-bg,transparent)}" &
			".nbgl{background:var(--pbi-theme-bg-light,transparent)}" &
			".nbgn{background:var(--pbi-theme-bg-neutral,transparent)}" &
			".nfgsel{background:var(--pbi-theme-fg-selected,transparent)}" &
			".nhl{background:var(--pbi-theme-hyperlink,transparent)}" &
			"</style>" &
			"<div class='tcp'>" &
			"<div class='hcflag'>HIGH CONTRAST ACTIVE (.pbi-theme-hc)</div>" &
			"<div class='grp'><h4>Theme colors</h4><div class='sw'>" &
			"<div class='s c1'><span>color-1</span></div>" &
			"<div class='s c2'><span>color-2</span></div>" &
			"<div class='s c3'><span>color-3</span></div>" &
			"<div class='s c4'><span>color-4</span></div>" &
			"<div class='s c5'><span>color-5</span></div>" &
			"<div class='s c6'><span>color-6</span></div>" &
			"<div class='s c7'><span>color-7</span></div>" &
			"<div class='s c8'><span>color-8</span></div>" &
			"<div class='s c9'><span>color-9</span></div>" &
			"<div class='s c10'><span>color-10</span></div>" &
			"<div class='s c11'><span>color-11</span></div>" &
			"<div class='s c12'><span>color-12</span></div>" &
			"</div></div>" &
			"<div class='grp'><h4>Sentiment colors</h4><div class='sw'>" &
			"<div class='s ngood'><span>good</span></div>" &
			"<div class='s nbad'><span>bad</span></div>" &
			"<div class='s nneu'><span>neutral</span></div>" &
			"</div></div>" &
			"<div class='grp'><h4>Divergent colors</h4><div class='sw'>" &
			"<div class='s nmin'><span>min</span></div>" &
			"<div class='s ncenter'><span>center</span></div>" &
			"<div class='s nmax'><span>max</span></div>" &
			"</div></div>" &
			"<div class='grp'><h4>High contrast colors</h4><div class='sw'>" &
			"<div class='s nfg'><span>fg</span></div>" &
			"<div class='s nbg'><span>bg</span></div>" &
			"<div class='s nfgsel'><span>fg-selected</span></div>" &
			"<div class='s nhl'><span>hyperlink</span></div>" &
			"</div></div>" &
			"<div class='grp'><h4>Other colors</h4><div class='sw'>" &
			"<div class='s nfg'><span>fg</span></div>" &
			"<div class='s nfgs'><span>fg-neutral-secondary</span></div>" &
			"<div class='s nfgt'><span>fg-neutral-tertiary</span></div>" &
			"<div class='s nbg'><span>bg</span></div>" &
			"<div class='s nbgl'><span>bg-light</span></div>" &
			"<div class='s nbgn'><span>bg-neutral</span></div>" &
			"<div class='s nfgsel'><span>fg-selected</span></div>" &
			"<div class='s nhl'><span>hyperlink</span></div>" &
			"</div></div>" &
			"</div>"
			
			```
		lineageTag: f8e81816-56a1-4df7-a712-d1ad1fd56abc

	column id
		dataType: string
		lineageTag: e9c1f291-cffa-4049-a290-19ca9ba98bad
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 6365f774-1e65-455d-8683-bbaab1a374dc
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column expected_outcome
		dataType: string
		lineageTag: 55bad994-9972-4da1-b688-9aad87cd2879
		summarizeBy: none
		sourceColumn: expected_outcome

		annotation SummarizationSetBy = Automatic

	column html_input
		dataType: string
		lineageTag: 0a902588-0b98-48d3-bf91-840bb99b274a
		summarizeBy: none
		sourceColumn: html_input

		annotation SummarizationSetBy = Automatic

	column html_sanitized
		dataType: string
		lineageTag: 9738c723-9061-4fc8-985f-e648b665208b
		summarizeBy: none
		sourceColumn: html_sanitized

		annotation SummarizationSetBy = Automatic

	column css_input
		dataType: string
		lineageTag: 16ce5d8e-4d58-4a9f-a54d-fe1843814515
		summarizeBy: none
		sourceColumn: css_input

		annotation SummarizationSetBy = Automatic

	column css_sanitized
		dataType: string
		lineageTag: 7042c494-8fde-468e-9e6c-01f49a890162
		summarizeBy: none
		sourceColumn: css_sanitized

		annotation SummarizationSetBy = Automatic

	partition stylesheet = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(RepoRoot & "\stylesheet.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"description", type text}, {"expected_outcome", type text}, {"html_input", type text}, {"html_sanitized", type text}, {"css_input", type text}, {"css_sanitized", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

