// Prestep run before `pbiviz package`/`start`/`test`. Writes the two git-ignored
// edition artifacts: the sanitizer backend selector and the active-edition
// handoff that pbiviz.mjs reads. Capabilities are committed files (capabilities.json
// / capabilities.webaccess.json); pbiviz.mjs selects the path, so nothing is
// generated for them here.
import { readFileSync, writeFileSync } from 'node:fs';
import { editions } from '../config/editions.mjs';

const edition = process.argv[2] ?? 'certified';
const e = editions[edition];
if (!e) {
    console.error(`Unknown edition: ${edition}`);
    process.exit(1);
}

const backend = e.sanitize ? 'backend.certified' : 'backend.passthrough';
writeFileSync(
    new URL('../src/sanitize/backend.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export * from './${backend}';\n`
);

writeFileSync(
    new URL('../config/active-edition.mjs', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export default '${edition}';\n`
);

const base = JSON.parse(
    readFileSync(new URL('../pbiviz.json', import.meta.url), 'utf8')
);
const resolvedVisual = { ...base.visual, ...e.visual };
writeFileSync(
    new URL('../src/visual-config.generated.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export type Edition = 'flagship' | 'secure' | 'standalone';\n` +
        `export const EDITION: Edition = '${e.edition}';\n` +
        `export const RESOLVED_VISUAL = ${JSON.stringify(
            resolvedVisual,
            null,
            4
        )} as const;\n`
);

const MARK_FILE = {
    flagship: 'shield.svg',
    secure: 'shield-secure.svg',
    standalone: 'shield-standalone.svg'
};
writeFileSync(
    new URL('../src/landing-mark.generated.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `import mark from '../assets/${MARK_FILE[e.edition]}';\n` +
        `export const MARK_URL: string = mark;\n`
);

console.log(
    `Selected edition: ${edition} (sanitize=${e.sanitize}, backend=${backend})`
);
