// Prestep run before `pbiviz package`/`start`/`test`. Writes the two git-ignored
// edition artifacts: the sanitizer backend selector and the active-edition
// handoff that pbiviz.mjs reads. Capabilities are committed files (capabilities.json
// / capabilities.webaccess.json); pbiviz.mjs selects the path, so nothing is
// generated for them here.
import { writeFileSync } from 'node:fs';
import { editions } from '../config/editions.mjs';

const edition = process.argv[2] ?? 'certified';
const e = editions[edition];
if (!e) {
    console.error(`Unknown edition: ${edition}`);
    process.exit(1);
}

const backend = e.sanitize ? 'backend.certified' : 'backend.passthrough';
writeFileSync(
    new URL('../src/sanitize/backend.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export * from './${backend}';\n`
);

writeFileSync(
    new URL('../config/active-edition.mjs', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export default '${edition}';\n`
);

console.log(
    `Selected edition: ${edition} (sanitize=${e.sanitize}, backend=${backend})`
);
