// Prestep run before `pbiviz package`/`start`/`test`. Writes the two git-ignored
// edition artifacts: the sanitizer backend selector and the active-edition
// handoff that pbiviz.mjs reads. Capabilities are committed files (capabilities.json
// / capabilities.webaccess.json); pbiviz.mjs selects the path, so nothing is
// generated for them here.
//
// Usage: node scripts/select-edition.mjs <edition> [channel]
//   edition: certified | standard | standalone   (default: certified)
//   channel: alpha | beta                        (optional; prerelease builds
//            get a channel-prefixed GUID, a displayName suffix and a channel
//            icon — see resolveEditionConfig in config/editions.mjs)
//   Channel builds must be followed by `npx pbiviz package` directly — `npm
//   run package` and `npm test` reset the selection to certified via their
//   pre-hooks.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolveEditionConfig } from '../config/editions.mjs';

const edition = process.argv[2] ?? 'certified';
const channel = process.argv[3];

const base = JSON.parse(
    readFileSync(new URL('../pbiviz.json', import.meta.url), 'utf8')
);
let resolved;
try {
    resolved = resolveEditionConfig(base, edition, channel);
} catch (err) {
    console.error(err.message);
    process.exit(1);
}

const MARK_FILE = {
    flagship: 'shield.svg',
    secure: 'shield-secure.svg',
    standalone: 'shield-standalone.svg'
};
const markFile = MARK_FILE[resolved.edition];
if (!markFile) {
    console.error(
        `No mark asset defined for edition '${resolved.edition}' (edition key: ${edition})`
    );
    process.exit(1);
}

const backend = resolved.sanitize ? 'backend.certified' : 'backend.passthrough';
writeFileSync(
    new URL('../src/sanitize/backend.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export * from './${backend}';\n`
);

writeFileSync(
    new URL('../config/active-edition.mjs', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export default '${edition}';\n` +
        `export const channel = ${channel ? `'${channel}'` : 'undefined'};\n`
);

writeFileSync(
    new URL('../src/visual-config.generated.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `export type Edition = 'flagship' | 'secure' | 'standalone';\n` +
        `export const EDITION: Edition = '${resolved.edition}';\n` +
        `export const RESOLVED_VISUAL = ${JSON.stringify(
            resolved.visual,
            null,
            4
        )} as const;\n`
);

writeFileSync(
    new URL('../src/landing/mark.generated.ts', import.meta.url),
    `// GENERATED by scripts/select-edition.mjs — do not edit.\n` +
        `import mark from '../../assets/${markFile}';\n` +
        `export const MARK_URL: string = mark;\n`
);

console.log(
    `Selected edition: ${edition}${channel ? ` (${channel} channel)` : ''} (sanitize=${resolved.sanitize}, backend=${backend})`
);
